vuejs-translations/docs-it

- .vitepress/config.ts
- src/guide/introduction.md
- src/guide/quick-start.md
la pagina era completamente in inglese
aggiunta una prima versione di traduzione, con alcuni compromessi stilistici
nessuna
> Taduzione per Quick-Start : Avvio Rapido - pronta per la revisione

- src/guide/typescript/composition-api.md
- src/guide/typescript/options-api.md
- src/guide/typescript/overview.md
> 19 guida typescript

- .vitepress/config.ts
- src/guide/essentials/application.md
- src/guide/essentials/class-and-style.md
- src/guide/essentials/component-basics.md
- src/guide/essentials/computed.md
- src/guide/essentials/conditional.md
- src/guide/essentials/event-handling.md
- src/guide/essentials/forms.md
- src/guide/essentials/lifecycle.md
- src/guide/essentials/list.md
- src/guide/essentials/reactivity-fundamentals.md
- src/guide/essentials/template-refs.md
- src/guide/essentials/template-syntax.md
- src/guide/essentials/watchers.md
traduzione per la guida.essentials mancante
traduzione effettuata
nessuna
@francescogropplero @JarielGFox  procedo anche al merge sul main
> 13 guideessentials

- src/about/team/members-partner.json
Updating my info.
DAL Main Ufficiale un piccolo merge indolore nel json dei partners
> chore: update team member (#2458)

- .vitepress/config.ts
Aggiornati testi per le label del template
Aggiornare i testi per prev-next- toc e altri legati al template vitepress
modifiche effettuate in i18n del config.ts
> config.ts i18n translation

- .vitepress/config.ts
- src/guide/reusability/composables.md
- src/guide/reusability/custom-directives.md
- src/guide/reusability/plugins.md
Description of Problem
Pagine della guide.reusability da tradurre
Proposed Solution
traduzione completata
traduzione completata
> 15 guidereusability

- src/guide/components/attrs.md
- src/guide/components/events.md
- src/guide/components/props.md
- src/guide/components/provide-inject.md
- src/guide/components/slots.md
- src/guide/components/v-model.md
- src/tutorial/TutorialRepl.vue
> 14 guidecomponents

- src/ecosystem/newsletters.md
- src/ecosystem/themes/ThemeListItem.vue
- src/ecosystem/themes/ThemePage.vue
- src/ecosystem/themes/ThemeProduct.vue
- src/ecosystem/themes/themes.json
pagine sezione Ecosystem e json dei temi dei partners
Traduzione completata
nessuna
> Traduzione pagine :ecosystem e json temi partners

- src/api/built-in-components.md
- src/api/composition-api-setup.md
- src/api/options-composition.md
- src/guide/built-ins/keep-alive-demos/CompA.vue
- src/guide/built-ins/keep-alive-demos/CompB.vue
- src/guide/built-ins/keep-alive.md
- src/guide/built-ins/suspense.md
- src/guide/built-ins/teleport.md
- src/guide/built-ins/transition-demos/Basic.vue
- src/guide/built-ins/transition-demos/BetweenComponents.vue
- src/guide/built-ins/transition-demos/BetweenElements.vue
- src/guide/built-ins/transition-demos/CssAnimation.vue
- src/guide/built-ins/transition-demos/ListBasic.vue
- src/guide/built-ins/transition-demos/ListMove.vue
- src/guide/built-ins/transition-demos/NestedTransitions.vue
- src/guide/built-ins/transition-demos/SlideFade.vue
- src/guide/built-ins/transition-group.md
- src/guide/built-ins/transition.md
- src/guide/essentials/component-basics.md
- src/guide/extras/render-function.md
Sezione Guida / built-ins da tradurre
file tradotti
nulla
> 16 guidebuilt ins

- src/guide/scaling-up/routing.md
- src/guide/scaling-up/sfc.md
- src/guide/scaling-up/ssr.md
- src/guide/scaling-up/state-management.md
- src/guide/scaling-up/testing.md
- src/guide/scaling-up/tooling.md
> 17 guidescaling up

- src/glossary/index.md
Pagina Sezione Glossario non tradotta
Presa in carico, traduzione necessaria
File lungo, creo una PR in draft per procedere a step
> 29 glossary index

- src/api/ApiIndex.vue
- src/api/custom-renderer.md
- src/api/render-function.md
- src/api/ssr.md
- src/api/utility-types.md
- src/guide/introduction.md
- src/sponsor/index.md
Sezione intera
Completata, fare review
> 21 api root

- .gitignore
- src/tutorial/TutorialRepl.vue
- src/tutorial/src/step-1/App/template.html
- src/tutorial/src/step-1/description.md
> 54 tutorialstep 1

- src/tutorial/src/step-2/App/composition.js
- src/tutorial/src/step-2/App/options.js
- src/tutorial/src/step-2/App/template.html
- src/tutorial/src/step-2/description.md
> feat(#55): tutorial step 2

- src/tutorial/src/step-3/App/template.html
- src/tutorial/src/step-3/_hint/App/template.html
- src/tutorial/src/step-3/description.md
> feat(#56): tutorial step 3

- src/tutorial/src/step-4/App/template.html
- src/tutorial/src/step-4/_hint/App/template.html
- src/tutorial/src/step-4/description.md
> feast(#57): tutorial step 4

- src/tutorial/src/step-5/_hint/App/template.html
- src/tutorial/src/step-5/description.md
> feat(#58): tutorial step 5

- src/tutorial/src/step-6/App/template.html
- src/tutorial/src/step-6/_hint/App/template.html
- src/tutorial/src/step-6/description.md
> feat(#59): tutorial step 6

- src/tutorial/src/step-8/App/template.html
- src/tutorial/src/step-8/_hint/App/template.html
- src/tutorial/src/step-8/description.md
> feat(#61): tutorial step 8

- src/tutorial/src/step-7/App/composition.js
- src/tutorial/src/step-7/App/options.js
- src/tutorial/src/step-7/App/template.html
- src/tutorial/src/step-7/_hint/App/composition.js
- src/tutorial/src/step-7/_hint/App/options.js
- src/tutorial/src/step-7/description.md
> feat(#60): tutorial step 7

- src/tutorial/src/step-10/App/template.html
- src/tutorial/src/step-10/description.md
> feat(#63): tutorial step 10

- src/tutorial/src/step-11/App/composition.js
- src/tutorial/src/step-11/App/options.js
- src/tutorial/src/step-11/App/template.html
- src/tutorial/src/step-11/ChildComp/template.html
- src/tutorial/src/step-11/description.md
> feat(#64): tutorial step 11

- src/api/application.md
- src/api/general.md
Pagine sezione API Globali
traduzione dei contenuti
> 22 api-global api

- src/tutorial/src/step-9/App/template.html
- src/tutorial/src/step-9/description.md
> feat(#62): tutorial step 9

- src/tutorial/src/step-14/App/composition.js
- src/tutorial/src/step-14/App/options.js
- src/tutorial/src/step-14/ChildComp/template.html
- src/tutorial/src/step-14/_hint/App/template.html
- src/tutorial/src/step-14/description.md
> feat: tutorial step 14

- src/tutorial/src/step-15/description.md
> feat: tutorial step 15

- src/examples/src/cells/store.js
> feat: examples/cells

- src/tutorial/src/step-13/App/composition.js
- src/tutorial/src/step-13/App/options.js
- src/tutorial/src/step-13/description.md
> feat: tutorial step 13

- src/examples/src/circle-drawer/App/template.html
Traduzione examples/circle-drawer
> feat: examples/circle-drawer

- src/examples/src/conditionals-and-loops/App/template.html
- src/examples/src/conditionals-and-loops/description.txt
Traduzione examples/conditionals and loops
> feat: examples/conditionals-and-loops

- src/examples/src/tree/App/composition.js
- src/examples/src/tree/App/options.js
- src/examples/src/tree/TreeItem/composition.js
- src/examples/src/tree/TreeItem/options.js
- src/examples/src/tree/TreeItem/template.html
- src/examples/src/tree/description.txt
> feat: examples/tree

- src/examples/src/todomvc/App/composition.js
- src/examples/src/todomvc/App/options.js
- src/examples/src/todomvc/App/template.html
- src/examples/src/todomvc/description.txt
> feat: examples/todo mvc

- src/examples/src/temperature-converter/App/template.html
Traduzione examples/ temperature-converter
> feat: examples/tempreature-converter

- src/examples/src/markdown/App/composition.js
- src/examples/src/markdown/App/options.js
- src/examples/src/markdown/description.txt
> feat: examples/markdown

- src/examples/src/timer/App/template.html
- src/examples/src/todomvc/description.txt
> feat: examples/timer

- src/examples/src/svg/App/composition.js
- src/examples/src/svg/App/options.js
- src/examples/src/svg/App/template.html
- src/examples/src/svg/PolyGraph/options.js
- src/examples/src/svg/description.txt
> feat: examples/svg

- src/examples/src/simple-component/App/composition.js
- src/examples/src/simple-component/App/template.html
- src/examples/src/simple-component/description.txt
Traduzione example/simple componente
> 48 examples/ simple component

- src/examples/src/modal/App/template.html
- src/examples/src/modal/Modal/style.css
- src/examples/src/modal/Modal/template.html
- src/examples/src/modal/description.txt
> feat: example/modal

- src/examples/src/grid/App/composition.js
- src/examples/src/grid/App/options.js
- src/examples/src/grid/App/template.html
- src/examples/src/grid/description.txt
> feat: examples/grid

- src/examples/src/list-transition/App/style.css
- src/examples/src/list-transition/App/template.html
- src/examples/src/list-transition/description.txt
Traduzione examples/list-transistion
> feat: examples/list-transition

- src/examples/src/handling-input/App/composition.js
- src/examples/src/handling-input/App/options.js
- src/examples/src/handling-input/App/template.html
- src/examples/src/handling-input/description.txt
Traduzione examples/handling-input
> feat: examples/handling-input

- src/examples/src/hello-world/App/composition.js
- src/examples/src/hello-world/App/options.js
- src/examples/src/hello-world/description.txt
Traduzione examples/hello-world
> feat: examples/hello-world

- src/examples/src/form-bindings/App/composition.js
- src/examples/src/form-bindings/App/options.js
- src/examples/src/form-bindings/App/template.html
- src/examples/src/form-bindings/description.txt
Traduzione examples/form-bindings
> feat: examples/form-bindings

- src/examples/src/counter/App/template.html
> feat: examples/counter

- src/examples/src/flight-booker/App/composition.js
- src/examples/src/flight-booker/App/options.js
- src/examples/src/flight-booker/App/template.html
Traduzione examples/flight-booker
> feat: examples/flight-booker

- src/examples/src/fetching-data/App/composition.js
- src/examples/src/fetching-data/App/options.js
- src/examples/src/fetching-data/App/template.html
- src/examples/src/fetching-data/description.txt
Traduzione examples/fetching-data
> feat: examples/fetching-data

- src/examples/src/crud/App/template.html
> feat: examples/crud

- src/examples/src/attribute-bindings/App/composition.js
- src/examples/src/attribute-bindings/App/options.js
- src/examples/src/attribute-bindings/App/template.html
- src/examples/src/attribute-bindings/description.txt
> 33 examplesattribute bindings

- .vitepress/config.ts
- src/translations/index.md
Missing official Italian translation links
added Italian Translation link and others from main repo
> Updated config.ts and src_translations_index

- CONTRIBUTING.md
This resolve issue #156
Some links point to the old repository
Edited link from the old repo url to the new repo url
> fix: #156 - Update CONTRIBUTING.md

- src/guide/extras/reactivity-in-depth.md
> reactivity-in-depth translated

- src/partners/components/PartnerAll.vue
- src/partners/components/PartnerCard.vue
- src/partners/components/PartnerHero.vue
- src/partners/components/PartnerJoin.vue
- src/partners/components/PartnerLanding.vue
- src/partners/components/PartnerList.vue
- src/partners/components/PartnerPage.vue
Tradotti componenti partners/components (issue #31)
> docs: partners/components (#31)

- src/guide/extras/rendering-mechanism.md
> Traduzione #Meccanismo di rendering
